export const users = [
  {
    id: "1",
    username: "freeman.dicki",
    name: "Freeman Dicki",
    email: "freeman83@gmail.com",
    phone: "+16972759140",
    status: "Invited",
    role: "Cashier",
  },
  {
    id: "2",
    username: "nick.bashirian-lowe",
    name: "Nick Bashirian-Lowe",
    email: "nick_donnelly@gmail.com",
    phone: "+17425632370",
    status: "Invited",
    role: "Admin",
  },
  {
    id: "3",
    username: "ardith_jast",
    name: "Ardith Jast",
    email: "ardith_crist@gmail.com",
    phone: "+13553118532",
    status: "Suspended",
    role: "Cashier",
  },
  {
    id: "4",
    username: "jeffrey_collins81",
    name: "Jeffrey Collins",
    email: "jeffrey.stark98@hotmail.com",
    phone: "+14646410541",
    status: "Inactive",
    role: "Manager",
  },
  {
    id: "5",
    username: "ashton.auer",
    name: "Ashton Auer",
    email: "ashton_hegmann67@yahoo.com",
    phone: "+14345495030",
    status: "Suspended",
    role: "Superadmin",
  },
  {
    id: "6",
    username: "golda.gleason",
    name: "Golda Gleason",
    email: "golda.smith32@gmail.com",
    phone: "+14606427316",
    status: "Active",
    role: "Manager",
  },
  {
    id: "7",
    username: "maurine.rutherford",
    name: "Maurine Rutherford",
    email: "maurine_bechtelar@gmail.com",
    phone: "+16544865144",
    status: "Suspended",
    role: "Manager",
  },
  {
    id: "8",
    username: "alford.wehner",
    name: "Alford Wehner",
    email: "alford36@hotmail.com",
    phone: "+12134843128",
    status: "Active",
    role: "Manager",
  },
  {
    id: "9",
    username: "theresa_rolfson46",
    name: "Theresa Rolfson",
    email: "theresa.mertz@yahoo.com",
    phone: "+17353031624",
    status: "Suspended",
    role: "Cashier",
  },
  {
    id: "10",
    username: "buford.bradtke",
    name: "Buford Bradtke",
    email: "buford68@yahoo.com",
    phone: "+16715125120",
    status: "Suspended",
    role: "Cashier",
  },
  // Additional users for pagination demo
  {
    id: "11",
    username: "jane.doe",
    name: "Jane Doe",
    email: "jane.doe@example.com",
    phone: "+15551234567",
    status: "Active",
    role: "Admin",
  },
  {
    id: "12",
    username: "john.smith",
    name: "John Smith",
    email: "john.smith@example.com",
    phone: "+15559876543",
    status: "Active",
    role: "Manager",
  },
  {
    id: "13",
    username: "emily.johnson",
    name: "Emily Johnson",
    email: "emily.j@example.com",
    phone: "+15552345678",
    status: "Invited",
    role: "Cashier",
  },
  {
    id: "14",
    username: "michael.brown",
    name: "Michael Brown",
    email: "m.brown@example.com",
    phone: "+15553456789",
    status: "Inactive",
    role: "Cashier",
  },
  {
    id: "15",
    username: "sarah.wilson",
    name: "Sarah Wilson",
    email: "sarah.w@example.com",
    phone: "+15554567890",
    status: "Active",
    role: "Manager",
  },
  {
    id: "16",
    username: "david.lee",
    name: "David Lee",
    email: "david.lee@example.com",
    phone: "+15555678901",
    status: "Suspended",
    role: "Admin",
  },
  {
    id: "17",
    username: "lisa.anderson",
    name: "Lisa Anderson",
    email: "lisa.a@example.com",
    phone: "+15556789012",
    status: "Active",
    role: "Cashier",
  },
  {
    id: "18",
    username: "chris.taylor",
    name: "Chris Taylor",
    email: "chris.t@example.com",
    phone: "+15557890123",
    status: "Invited",
    role: "Manager",
  },
  {
    id: "19",
    username: "amy.martinez",
    name: "Amy Martinez",
    email: "amy.m@example.com",
    phone: "+15558901234",
    status: "Active",
    role: "Superadmin",
  },
  {
    id: "20",
    username: "kevin.garcia",
    name: "Kevin Garcia",
    email: "kevin.g@example.com",
    phone: "+15559012345",
    status: "Inactive",
    role: "Cashier",
  },
];
